#ifndef FREE_BIKE_PROJECT_REPOSITORY_CONTROLLEROSM_H
#define FREE_BIKE_PROJECT_REPOSITORY_CONTROLLEROSM_H

class ControllerOSM{
public:
    ControllerOSM();
    ~ControllerOSM();
};
#endif //FREE_BIKE_PROJECT_REPOSITORY_CONTROLLEROSM_H
